# Generated by Django 5.0.3 on 2024-06-11 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_No', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_No', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=16)),
                ('shipping_address', models.CharField(max_length=60)),
                ('contact', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_No', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('order_Date', models.DateField(auto_now=True)),
                ('total_Price', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.customer')),
                ('order_Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.orderstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_No', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_colour', models.CharField(max_length=30)),
                ('category', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='crud.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('orderItem_No', models.CharField(blank=True, max_length=12, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price_at_order_time', models.IntegerField()),
                ('order_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.order')),
                ('product_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.customer')),
                ('product_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.product')),
            ],
        ),
    ]
