# Generated by Django 5.0.3 on 2024-06-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_No',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
